const listTitle = [
    // A
    'AWOKW AWOKW',
    // B
    'Baik Pak!',
    // C
    // D
    // E
    // F
    // G
    'Gweh Banget',
    'Gweh Ganteng',
    'Gweh Keren',
    // H
    'Haah Brodies',
    "Ha'aa Laah",
    'Halo Cantik',
    'Halo Ganteng',
    'Hello Girls.',
    'Hello World',
    'Hihi Haha',
    'Huhu Heho',
    'Holla Weirdo.',
    // I
    // J
    'Jirr Laah!',
    // K
    'Keren Banget',
    'Knp Bro?',
    'Knp Lah?',
    // L
    'Looo Keren',
    'Lo Jelek',
    'Lo Keren',
    "Luuh Keren",
    // M
    'Maaf Laah',
    'Masa Sih?',
    // N
    "Not Defined",
    // O
    "Oke Sip",
    // P
    // Q
    // R
    'Reqq Reqq',
    'Resaa Jelek',
    'Resaa Cantik',
    'Resaa Keren:',
    'Resaa Aneh!!',
    // S
    'Siap Pak!!',
    // T
    'Tareq Krenn',
    'Tareq Gantenk',
    // U
    // V
    // W
    'Wasup Bro',
    'Wasup Bro',
    'Weee Wooo',
    'Wihii Wuhuu',
    'Wkwk Wkwk',
    // X
    // Y
    // Z
    'zzz zzz',
    '... Hah?',
    '... Huh?',
    '... Heh?',
    '10110 10110'
]